Update multi-job.yml

diff --git a/.github/workflows/multi-job.yml b/.github/workflows/multi-job.yml
--- a/.github/workflows/multi-job.yml
+++ b/.github/workflows/multi-job.yml
@@ -1,71 +1,39 @@
-name: "multi-job"
-
-on: 
+---
+name: multi-job
+on:
   push:
     branches:
       - main
-
-# env:
-#   APP_NAME: myapp
-
 jobs:
-  build:
+  main-check:
     runs-on: ubuntu-latest
     outputs:
       my_value: ${{ steps.step1.outputs.date }}
-
     steps:
-      - name: "create output"
+      - name: create output
         id: step1
+        if: ${{ github.ref =='main' }}
         run: echo "date=$(date)" >> $GITHUB_OUTPUT
-  usage:
-    
-      runs-on: ubuntu-latest
-      needs: build
-      steps:
-      - name: "print output"
-        run: echo "${{ needs.build.outputs.my_value }}"
-    # env:
-    #   ENVIRONMENT: staging
-
-  #   steps:
-  #     - name: "build stage"
-  #       env:
-  #         VERSION: 1.0.0
-  #       run: |
-  #         echo "App: $APP_NAME"
-  #         echo "Env: $ENVIRONMENT"
-  #         echo "Version: $VERSION"
-  #         echo "COMMIT SHA: ${{ github.sha }}"
-  #         echo "ACTOR: ${{ github.actor }}"
-  # # test:
-  #   needs: build
-  #   runs-on: ubuntu-latest
-
-  #   env:
-  #     ENVIRONMENT: staging
-
-  #   steps:
-  #     - name: "test stage"
-  #       env:
-  #         VERSION: 1.0.0
-  #       run: |
-  #         echo "App: $APP_NAME"
-  #         echo "Env: $ENVIRONMENT"
-  #         echo "Version: $VERSION"
-
-  # deploy:
-  #   needs: test
-  #   runs-on: ubuntu-latest
-
-  #   env:
-  #     ENVIRONMENT: staging
-
-  #   steps:
-  #     - name: "deploy stage"
-  #       env:
-  #         VERSION: 1.0.0
-  #       run: |
-  #         echo "App: $APP_NAME"
-  #         echo "Env: $ENVIRONMENT"
-  #         echo "Version: $VERSION"
+  fail-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Step 1 (will fail)
+        run: exit 1
+      - name: Run only if previous step failed
+        if: ${{ failure() }}
+        run: echo "Previous step failed!"
+  push-check:
+    runs-on: ubuntu-latest
+   
+    steps:
+      - name: Run only on push
+        if: ${{ github.event_name == 'push' }}
+        run: echo "This runs only on push events"
+  failevent-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Step that may fail
+        continue-on-error: true
+        run: exit 1
+      - name: Next step
+        run: echo "Workflow continues"
